### PR TITLE
[cgc-2]initial commit for new branch

### PR DESCRIPTION
**Pull request by Claire-Gao0930**
# Pull Request Template

## Summary
I am starting with 'contract' api. This is a test for creating new branch from forked repo

### CODE REVIEW

**Comment by juanpalopez** [comment]
Awesome, thanks for starting to collaborate; it looks great! I have linked the `issue` in the development section on the right side. Would you mind renaming this to cgc-9? I think in the future, it will be easier to create the branch from the issue in the `project` for linking branches and issues.

**Review by juanpalopez — APPROVED** [review]
good-job

**Comment by Claire-Gao0930** [comment]
Sure thing!The branch name has been changed to cgc-9-contract.

**Comment by Claire-Gao0930** [comment]
Sure thing!The branch name has been changed to cgc-9-contract.

**Pull request closed without merging**
